nelmio_api_doc:
    documentation:
        info:
            title: Coding challenge
            description: A api documentation
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/(?!doc(.json)?$) # Accepts routes under /api except /api/doc
