parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/*'
        exclude:
            - '../src/{DependencyInjection,Tests,Kernel.php}'
            - '../src/Application/DTO'
            - '../src/Domain/Model'
            - '../src/Infrastructure/Doctrine/Migrations'

    App\Infrastructure\Symfony\Controller\:
        resource: '../src/Infrastructure/Symfony/Controller'
        tags: ['controller.service_arguments']

    App\Infrastructure\Serializer\Normalizer:
        public: false
        arguments:
            $factories: !tagged app.infrastructure.serializer_factory
        tags:
            - 'serializer.normalizer'
