App\Application\DTO\Place\Create:
    properties:
        name:
            - Type: string
            - NotBlank: ~
        type:
            - App\Infrastructure\Symfony\Validator\Constraints\Place\ValidType: ~
        latitude:
            - Type: float
            - App\Infrastructure\Symfony\Validator\Constraints\Geolocation\Position\ValidLatitude: ~
        longitude:
            - Type: float
            - App\Infrastructure\Symfony\Validator\Constraints\Geolocation\Position\ValidLongitude: ~
